WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApp/Pages/Shops/Delete.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using ServiceLayer;

namespace WebApp.Pages.Shops
{
    public class DeleteModel : PageModel
    {
        private readonly IShopService _ShopService;

        [BindProperty(SupportsGet = true)]
        public int ShopId { get; set; }

        public Shop Shop { get; set; } = default!;

        public DeleteModel(IShopService shopService)
        {
            _ShopService = shopService;
        }

        public IActionResult OnGet()
        {
            Shop = _ShopService.GetShopById(ShopId);

            if (Shop == null)
            {
                return NotFound();
            }

            return Page();
        }

        public IActionResult OnGetDeleteShop()
        {
            bool result = _ShopService.Delete(ShopId);

            if (result)
            {
                return RedirectToPage("/Shops/List");
            }
            else
            {
                return BadRequest(); 
            }
        }
    }
}

WebApp/Pages/Shops/Detail.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Distributed;
using ServiceLayer;

namespace WebApp.Pages.Shops
{
    public class DetailModel : PageModel
    {
        public Shop Shop { get; set; }

        private readonly IShopService _ShopService = default!;

        private readonly IDistributedCache _cache = default!;

        public DetailModel(IShopService shopService,IDistributedCache cache)
        {
            _cache = cache;
            _ShopService = shopService;
        }

        public IActionResult OnGet(int shopId)
        {
            Shop = _ShopService.GetShopById(shopId);

            _cache.SetString("PageLastVisit",shopId.ToString());

            return Page();
        }
    }
}

WebApp/Pages/Shops/Edit.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServiceLayer;

namespace WebApp.Pages.Shops
{
    public class EditModel : PageModel
    {
        private readonly IShopService _ShopService;

        [BindProperty(SupportsGet = true)]
        public int ShopId { get; set; }

        public IEnumerable<SelectListItem> Types { get; set; } = default!;

        [BindProperty]
        public Shop Shop { get; set; } = default!;

        public EditModel(IShopService shopService)
        {
            _ShopService = shopService;
        }

        public IActionResult OnGet()
        {
            Shop = _ShopService.GetShopById(ShopId);

            if(Shop == null)
            {
                return RedirectToPage("./NotFound");
            }

            Types = _ShopService.GetShopTypes()
                                .Select(t => new SelectListItem(t.Name,t.ShopTypeId.ToString()))
                                .ToList();

            return Page();
        }

        public IActionResult OnPost()
        {
            try
            {
                _ShopService.Update(Shop);
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToPage("/Shops/Detail",new { ShopId = Shop.ShopId });
        }
    }
}

WebApp/Pages/Shops/List.cshtml.cs
using System.ComponentModel.DataAnnotations;
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceLayer;

namespace WebApp.Pages.Shops
{
    public class ListModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;

        public int PageVisited { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public int PageSize { get; set; } = 10;

        public int Count { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

        public enum PageSizeEnum
        {
            [Display(Name = "2")]
            _2 = 2,
            [Display(Name = "4")]
            _4 = 4,
            [Display(Name = "10")]
            _10 = 10,
        }

        public IEnumerable<Shop> Shops { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; } = default!;
  
        private readonly IShopService _ShopService = default!;
    
        public ListModel(IShopService ShopService)
        {
            _ShopService = ShopService;
        }
    
        public void OnGet()
        {
            ShopViewModel ShopModel = _ShopService.GetShopsByName(SearchTerm, CurrentPage, PageSize);
            Shops = ShopModel.Shops;
            Count = ShopModel.TotalCount; 

            try
            {
                int? shopId = HttpContext.Session.GetInt32("PageLastVisit");

                if (shopId != null)
                {
                    ViewData["PageVisited"] = shopId;
                }
            }
            catch {}
        }
    }
}

WebApp/ViewComponents/ShopCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;

namespace WebApp.ViewComponents
{
    public class ShopCountViewComponent : ViewComponent
    {
        private readonly IShopService _shopService;

        public ShopCountViewComponent(IShopService shopService)
        {
            _shopService = shopService;
        }

        public IViewComponentResult Invoke()
        {
            int count = _shopService.GetShopCount();
            return View(count);
        }
    }
}

WebApp/Pages/Shared/Components/ShopCount/Default.cshtml
@model int

<div id="ShopCount">
    <h4>There is @Model Shops</h4>
</div>

WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ShopIndex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/css/sitebundle.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ShopIndex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Shops/List">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-success nav-link text-dark" asp-area="" asp-page="/Shops/Create"><i class="fa fa-plus"></i> New</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @await Component.InvokeAsync("ShopCount")
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Pages/Shops/Create.cshtml
@page
@model WebApp.Pages.Shops.CreateModel

<div asp-validation-summary="All" ></div>

<form method="post" enctype="multipart/form-data" >

    <div class="form-group">
        <label asp-for="Shop.Name">Name</label>
        <input type="text" asp-for="Shop.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Shop.Name"></span>
    </div>
    <br>
    <div class="form-group">
        <label asp-for="Shop.Location">Location</label>
        <input type="text" asp-for="Shop.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Shop.Location"></span>
    </div>
    <br>
    <div class="form-group">
        <label asp-for="Shop.ShopTypeId">Type</label>
        <select asp-for="Shop.ShopTypeId"
                asp-items="Model.Types"
                class="form-control">
            <option value="" disabled>Choose ShopType</option>
        </select>
        <span class="text-danger" asp-validation-for="Shop.ShopTypeId"></span>
    </div>
    <br>

    <div class="form-group">
        <label asp-for="Shop.Image">Type</label>
        <input type="file" asp-for="Shop.Image" />
    </div>
    <br>

    <button class="btn btn-success"><i class="fa-solid fa-plus"></i> Add</button>

</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApp/Pages/Shops/Delete.cshtml
@page
@model DeleteModel

<h1>Are you Sure?</h1>

<h3>Delete @Model.Shop.Name?</h3>

<div class="alert alert-danger">This action cannot be reverted!</div>

<a class="btn btn-success p-2 w-25" asp-page-handler="DeleteShop" asp-route-ShopId="@Model.Shop.ShopId">Yes</a>
<a class="btn btn-danger p-2 w-25" asp-page="/Shops/List">No</a>

WebApp/Pages/Shops/Detail.cshtml
@page "{ShopId:int}"
@model WebApp.Pages.Shops.DetailModel
@{
    ViewData["Title"] = "Detail";
}
 
<h2>@Model.Shop.Name</h2>

<img src="@Model.Shop.ImageData.GetBase64Image(Model.Shop.ImageMimeType)" alt="@Model.Shop.Name" />

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Shop.ShopId)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Shop.ShopId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Shop.Location)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Shop.Location)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Shop.Type.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Shop.Type.Name)
    </dd>
</dl>
 
<a asp-page="./List" class="btn btn-info">All Shops</a>

WebApp/Pages/Shops/Edit.cshtml
@page "{ShopId:int}"
@model WebApp.Pages.Shops.EditModel


<form action="Post">
    <div class="form-group">
        <label asp-for="Shop.Name" />
        <input  type="text" asp-for="Shop.Name" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="Shop.Location" />
        <input type="text" asp-for="Shop.Location" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="Shop.Type" />
        <select asp-for="Shop.Type"
                asp-items="Model.Types"
                class="form-control">
            <option value="" disabled>Choose ShopType</option>
        </select>
    </div>

    <button><i class="fa-solid fa-floppy-disk"></i> Save</button>

</form>

WebApp/Pages/Shops/List.cshtml
@page
@model WebApp.Pages.Shops.ListModel

<form method="get">
    <div class="input-group mb-3">
        <input type="search" asp-for="@Model.SearchTerm" class="form-control">
        <div class="input-group-append">
            <select asp-for="@Model.PageSize"
                    asp-items="Html.GetEnumSelectList<WebApp.Pages.Shops.ListModel.PageSizeEnum>()"
                    class="custom-select">
                <option value="">Pagesize</option>
            </select>
            <button class="btn btn-outline-secondary" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </div>
        
    </div>
</form>


<profile name="Shoptable">
    <table class="table">
        <tbody>
            @foreach (var Shop in Model.Shops)
            {
                <partial name="_ListItemPartial" model="Shop" />
            }
        </tbody>
    </table>
</profile>


<div>
    <ul class="pagination">
        @for (var i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-page=""
                   asp-route-currentpage="@i" 
                   asp-route-searchTerm="@Model.SearchTerm" 
                   asp-route-pageSize="@Model.PageSize"
                   class="page-link">@i</a>
            </li>
        }
    </ul>
</div>

WebApp/Pages/Shops/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}
 
<h2>Your Shop was not found</h2>
<a asp-page="./List" class="btn btn-info">See All Shops</a>

WebApp/Pages/Shops/_ListItemPartial.cshtml
@model DataLayer.Entities.Shop

@{
    string TrClass = "";

    int? ShopId = Convert.ToInt32(ViewData["PageVisited"]);

    if(ShopId != null)
    {
        if (ShopId == Model.ShopId)
        {
            TrClass = "bg-info";
        }
    }
}

<tr class="@TrClass" >
    <td>@Model.Name</td>
    <td>@Model.Location</td>
    <td>@Model.Type.Name</td>
    <td>
        <a asp-page="/Shops/Detail" asp-route-ShopId="@Model.ShopId">
            <i class="fas fa-info-circle"></i>
        </a>
    </td>
    <td>
        <a asp-page="/Shops/Delete" asp-route-ShopId="@Model.ShopId">
            <i class="fas fa-trash"></i>
        </a>
    </td>
    <td>
        <a asp-page="/Shops/Edit" asp-route-ShopId="@Model.ShopId">
            <i class="fas fa-edit"></i>
        </a>
    </td>
</tr>